### ISSUE TITLE
TODO: Refactor

### ISSUE THREAD

**Issue by JackBekket** [JackBekket/Hellper#28]
- [x] cut functions calling commands from cases.go into main.go

- [x] create dialog handler and move all code from commander into new entity

- [x] make this function get input from channel and then call it from main.go transfering updates through chanel
- [x] transfer all code working with updates from main to dialog entity

- [x] run ai-generated auto_doc to clean-up and make documentation

**Comment by JackBekket** [comment]
done
